// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entity_framework.Context;

#nullable disable

namespace entity_framework.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20251008032617_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("entity_framework.Models.Categoria", b =>
                {
                    b.Property<Guid>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("peso")
                        .HasColumnType("int");

                    b.HasKey("categoriaId");

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            categoriaId = new Guid("c3db2d1e-b1ff-43c4-acfe-257f49916ae2"),
                            descripcion = "Tareas que debemos realizar en casa",
                            nombre = "En Casa",
                            peso = 2
                        },
                        new
                        {
                            categoriaId = new Guid("f5edfbfd-aa6c-4261-b24a-3ef3c85a5984"),
                            descripcion = "Tareas que requieren un desgaste físico",
                            nombre = "Ejercitar",
                            peso = 5
                        },
                        new
                        {
                            categoriaId = new Guid("99eb1cae-a854-4503-a1ac-bf13c2453271"),
                            descripcion = "Estudiar o practicar alguna habilidad",
                            nombre = "Estudiar",
                            peso = 3
                        });
                });

            modelBuilder.Entity("entity_framework.Models.Tarea", b =>
                {
                    b.Property<Guid>("tareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("categoiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("fechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("prioridad")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("tareaId");

                    b.HasIndex("categoiaId");

                    b.ToTable("tarea", (string)null);

                    b.HasData(
                        new
                        {
                            tareaId = new Guid("2afee021-4f8a-4a60-9824-1703695b23c3"),
                            categoiaId = new Guid("99eb1cae-a854-4503-a1ac-bf13c2453271"),
                            creacion = new DateTime(2025, 10, 7, 22, 26, 16, 962, DateTimeKind.Local).AddTicks(2688),
                            descripcion = "Realizar la ruta de desarrollo con .net",
                            estado = 1,
                            prioridad = 2,
                            titulo = "Aprender .net"
                        });
                });

            modelBuilder.Entity("entity_framework.Models.Tarea", b =>
                {
                    b.HasOne("entity_framework.Models.Categoria", "categoria")
                        .WithMany("tareas")
                        .HasForeignKey("categoiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("entity_framework.Models.Categoria", b =>
                {
                    b.Navigation("tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
